{
 "title": "CPU USE Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "Saturation over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cpu_saturation" },
    { "expr": "cpu_saturation_total" }
   ]
  },
  {
   "title": "Current CPU Saturation ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_saturation" }
   ]
  },
  {
   "title": "Run Queue Latency (in milisecs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "spent_cpu_latency{}" }
   ]
  },
  {
   "title": "Memory Usage in MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "mem_latency{}" }
   ]
  }
 ]
}