global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: leaky_webapp
    static_configs:
      - targets: ['161.35.0.6:9001']
